[ditaa]
.Pipeline
----

 +--------+ 0                                          +----------------------+
 |  MMML  +------------------------------------------->|{d} mmml.json         |
 | Wrapper|                                            +----------------------+
 |        |
 +-+----+-+ 1
   |    |
   |    |
   |    |
   |    |
   |    |
   |    :                               prepareProject +----------------------+
   |    +--------------------------------------------->|{d}buildweaver.json   |
   |                     +---------------------------->|                      |
   |                     |                             +----------------------+
   |                     |
   |                     |       +---------+           +----------------------+
   |                     |+----->|PP1:     +---------->|{s} src/main/mmml     |
   |                     ||   3  | cp -r   +           |                      |
   |                     ||      +----+----+           +----------------------+
   |                     ||           :
   |                     ||           +----------=---------------+ copyResources
   |                     ||                                      |
   |                     ||                                      V
   |         +--------+  ||      +---------+           +----------------------+
   |         |        +--+|+---->|PP2:     +---------->|{s} target/mmml       |
   |         |        +---+|  4  | find    |           |                      |
   |         | build  +----+     +----+----+           +----------------------+
   ++------->| weaver |               :
             |        +----+          +--------------------------+ prepareResources
             |        +---+|                                     |   process files in strokes directory
             |        |   ||                                     |   generate __index__.json files
             |        +--+||                                     V
             +--------+  |||  5  +---------+       5.1 +--------------------------+
                         ||+---->|PP3:     +---------->|{d}song.json++ (yaml/json)|
                         ||      | jq_front|           +--------------------------+
                         ||      +----+----+
                         ||           :
                         ||           +--------------------------+ preprocessSourceFiles
                         ||                                      |
                         ||                                  5.2 |
                         ||      +---------+                     V
                         ||      |         |       6.1 +----------------------+
                         |+----->|symfonion+---------->|{d}     song.json     |
                         |    6  |         |           +----------------------+
                         |       +--+----+-+
                         |          |    |
                         |          :    :
                         |          |    +-----------------------+ compileSourceFiles
                         |          | 6.2a1                  6.2b|
                         |          V                            V
             +--------+  |    2  +---------+       7.1 +----------------------+
             | OTHER  |  +------>|  SYNTH  +---------->|{d} MIDI files        |
             |        +--------->|(Yoshimi)|           +----------------------+
             | TOOLS  |       7  +----+----+
             +--------+               |
                                      :
                                      | 6.2a2
                                      V 7.2
                                 +---------+
                                 |  AUDIO  |
                                 +---------+
----

0: Prepare Project:: Render project definition file (`buildweaver.json`) for `buildweaver` tool.
1: Read Project Definition File:: At beginning, `buildweaver` reads its project definition file, `buildweaver.json` from the current working directory.
2: Prepare Synthesizers:: Based on the configuration, `mmml` starts synthesizers, such as `Yoshimi`<<Yoshimi>>.
3: Copy Resources:: Copy resources under source directory (`src/main/mmml`) to working directory (`target/mmml`).
4: Prepare Resources:: In this step, two things will be done.
First Convert files under `strokes` will be converted into patterns, and they will be stored under `patterns` directory.
See link:../directory-layout/home/{USER}/WORKSPACE/example-song/src/main/mmml/song/strokes/[`strokes`].
Then, traverse the copied resourced and find `\\__index__` files.
For each directory wih the file, generate `\\__index__.json`, which contains entries for JSON files in it.
Note that all those happen only under `target` directory.
5: Preprocess Source Files:: Then, `mmml` preprocesses YAML files to convert them into one JSON file using `jq-front`<<jq-front>> (5.1 and 5.2).
6: Compile Source Files:: Preprocessing stage generates a JSON file which `symfonion`<<symfonion>> can process.
`symfonion` compiles it into MIDI data.
The MIDI data is written to output files or directly sent to MIDI devices (music synthesizers; *5.2a1* and *5.2a2*).
6.1::: `symfonion` reads the JSON files
6.2a1::: Sends MIDI events to the MIDI devices, for instance Yoshimi, etc.
6.2a2::: The MIDI device sends AUDIO
6.2b::: In case, compile only mode is specified, instead of sending the MIDI events to sequencers, MIDI files will be generated.
7 Playback Compiled MIDI files:: The MIDI player `symfonion` has is a very simple one.
In case you want to play back the compiled MIDI files with features that it doesn't have or in an environment where it doesn't work, you need to use external tools.
7.1 and 7.2::: Your tool reads and reuses the compiled MIDI files.
