name: Java CI

on:
  push:
    branches: [ $default-branch, "master-**" ]
  pull_request:
    branches: [ $default-branch, "master-**" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 21
        cache: maven
    - name: list files in current directory
      working-directory: ${{ github.workspace }}
      run: ls -al
    - name: Build with Maven
      working-directory: ${{ github.workspace }}
      run: mvn -B package
