name: Java CI

on:
  push:
    branches: [ $default-branch, "master-**" ]
  pull_request:
    branches: [ $default-branch, "master-**" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 21
        cache: maven
    - name: Build with Maven
      run: mvn -B package
